### ISSUE TITLE
Checklist: add all tracks to TRACKS.json

### ISSUE THREAD

**Issue by SleeplessByte** [exercism/tracks-maintenance-dashboard#2]
https://github.com/exercism/tracks-maintenance-dashboard/blob/master/src/data/tracks.json

- [x] Ballerina
- [x] Bash
- [x] C
- [x] C#
- [x] C++
- [x] CFML
- [x] Clojure
- [x] CoffeeScript
- [x] Common Lisp
- [x] Crystal
- [x] D
- [x] Dart
- [x] Delphi Pascal
- [x] Elixir
- [x] Elm
- [x] Emacs Lisp
- [x] Erlang
- [x] F#
- [x] Go
- [x] Groovy
- [x] Haskell
- [x] Java
- [x] JavaScript
- [x] Julia
- [x] Kotlin
- [x] LFE
- [x] Lua
- [x] MIPS Assembly
- [x] Nim
- [x] Objective-C
- [x] OCaml
- [x] Perl 5
- [x] Perl 6
- [x] Pharo
- [x] PHP
- [x] PL/SQL
- [x] Prolog
- [x] PureScript
- [x] Python
- [x] R
- [x] Racket
- [x] ReasonML
- [x] Ruby
- [x] Rust
- [x] Scala
- [x] Scheme
- [x] Standard ML
- [x] Swift
- [x] TypeScript
- [x] Vim script
- [x] x86-64 Assembly

**Comment by kewbish** [comment]
Hi, I can help if you'd like.
AFAICS, it's just copy-pasting the names? How does the core-enabled work?

**Comment by SleeplessByte** [comment]
@kewbish core enabled was for another tool but let's set it anyway. It means that it has config.json and has at least one exercise with core set to true.

For example, in the JavaScript repo, you'll find a config.json file and within an exercises key with the first 19 exercises having core true.

**Comment by SleeplessByte** [comment]
You can run this repo locally by doing 
```
yarn
yarn start
```
Or
```
npm install
npm start
```

**Comment by SleeplessByte** [comment]
(P.S, there's already way more than I have check-off here)

**Comment by kewbish** [comment]
Should I also update the versioning info for each track?

**Comment by SleeplessByte** [comment]
Yes please. But it's easiest if you do them _either all together_ or _a PR per track_.

**Comment by kewbish** [comment]
I'll submit a PR with all the tracks added first.
Can't seem find the versioning in a consistent place, any idea where each is located?

**Comment by SleeplessByte** [comment]
It's not in a consistent place. That's why it has to be encoded into that key value thing.

I usually open a core exercise like two-fer and skim the files for version information.

**Comment by SleeplessByte** [comment]
Woosh. The tracks are all added via #11
