### ISSUE TITLE
Wrong slug format for Kotlin

### ISSUE THREAD

**Issue by dector** [exercism/tracks-maintenance-dashboard#43]
Now: `Exerciseslug`
Should be: `ExerciseSlug`

**Comment by SleeplessByte** [comment]
Arey you certain? If you look at [`two-fer`](https://github.com/exercism/kotlin/blob/master/exercises/two-fer) in the [`kotlin`](https://github.com/exercism/kotlin) track repo I see:

https://github.com/exercism/kotlin/blob/master/exercises/two-fer/src/test/kotlin/TwoferTest.kt

This _should_ have been `TwoFerTest.kt`

**Comment by dector** [comment]
@SleeplessByte Yes, I'm quite sure :smile: . We have [official code style guide](https://kotlinlang.org/docs/reference/coding-conventions.html#naming-rules) that says:

```
Names of classes and objects start with an upper case letter and use the camel case.
```

So unless "Twofer" is not used for [device](https://en.wikipedia.org/wiki/Twofer) - it should be `TwoFer`? You can try to search `Test.kt` [here](https://github.com/exercism/kotlin/find/master) for more examples.

**Comment by SleeplessByte** [comment]
Ok. In that case, please fix `two-fer` (it's dash-case equivalent should've been transformed to `TwoFer`). I'll merge your PR :)

**Comment by dector** [comment]
Sure! `two-fer` should be fixed. [Follow-up issue](https://github.com/exercism/kotlin/issues/336).

**Comment by dector** [comment]
Btw, should I open another issue for deploying this changes?
